#import "./CourseFragment.gql"
#import "./TeacherFragment.gql"
#import "./StudentFragment.gql"
#import "./UserFragment.gql"


subscription {
  courseAddedData {
    ...course
    teacher {
      ...teacher
    }
    students {
      ...student
    }
    createBy {
      ...user
    }
  }
}